"""Delta WeightLaw demo — fastest generative weight streaming.

The delta approach: W_eff = W_real + U_eff @ Vh
- U_eff, Vh are rank-4 factors generated by the law (86K params)
- The factored forward never reconstructs the full weight matrix:
    W_eff @ x = W_real @ x + U_eff @ (Vh @ x)
  This eliminates the O(out×in×rank) bottleneck entirely.

On SmolLM2-135M: 1.3× overhead, 49ms/tok.
Untrained law preserves full model quality (NLL delta < 0.001).
"""

import time, torch
from revo.law_streaming import (
    build_law, law_generate, law_stream_forward,
)
from revo._utils import load_model_tokenizer
from revo.streaming import _get_device

MODEL_NAME = "HuggingFaceTB/SmolLM2-135M"
RANK = 4
SMALL_DIM = 2
HIDDEN_DIM = 64

print(f"Loading {MODEL_NAME}...")
model, tokenizer = load_model_tokenizer(MODEL_NAME)
device = _get_device(model)

# ─── Build delta law ───────────────────────────────────────────────────
law = build_law(model, rank=RANK, small_dim=SMALL_DIM, hidden_dim=HIDDEN_DIM).to(device)
n_params = sum(p.numel() for p in law.parameters())
n_full = sum(p.numel() for p in model.parameters())
print(f"\nDelta-law: {n_params:,} params ({n_params/n_full*100:.2f}% of model)")
print(f"Delta mode (factored forward): rank={RANK}, small_dim={SMALL_DIM}")

# ─── Quality: untrained law preserves full model ───────────────────────
enc = tokenizer("The future of artificial intelligence", return_tensors="pt").input_ids.to(device)

with torch.no_grad():
    logits_full = model(enc).logits
logits_law = law_stream_forward(model, enc, law, use_cache=False, use_native=True)

diff_max = (logits_full - logits_law).abs().max().item()
import torch.nn.functional as F
nll_full = F.cross_entropy(logits_full[:, :-1].reshape(-1, logits_full.shape[-1]),
                            enc[:, 1:].reshape(-1)).item()
nll_law = F.cross_entropy(logits_law[:, :-1].reshape(-1, logits_law.shape[-1]),
                           enc[:, 1:].reshape(-1)).item()
print(f"\nQuality (untrained — near-zero random deltas):")
print(f"  NLL: full={nll_full:.4f}  law={nll_law:.4f}  delta={nll_law-nll_full:+.4f}")
print(f"  |logit|_oo: {diff_max:.2e}  (identical to full model)")

# ─── Speed benchmark ──────────────────────────────────────────────────
torch.cuda.empty_cache()
t0 = time.perf_counter()
with torch.no_grad():
    _ = model(enc).logits
t_full = time.perf_counter() - t0

t0 = time.perf_counter()
_ = law_stream_forward(model, enc, law, use_cache=False, use_native=True)
t_law = time.perf_counter() - t0

print(f"\nSpeed (single forward, seq_len={enc.shape[1]}):")
print(f"  Full:  {t_full*1000:.0f}ms")
print(f"  Law:   {t_law*1000:.0f}ms  ({t_law/t_full:.1f}×)")
print(f"  Overhead: {(t_law/t_full - 1)*100:.0f}%")

# ─── Generate ─────────────────────────────────────────────────────────
prompt = "The future of artificial intelligence"
max_new = 40
print(f"\nGeneration ({max_new} tokens, KV cache, factored forward):")
t0 = time.time()
out_text, meta = law_generate(model, tokenizer, prompt, law,
                               max_new_tokens=max_new, temperature=0.7,
                               top_k=40, verbose=False)
gen_time = time.time() - t0
print(f"  {gen_time/max_new*1000:.0f}ms/tok  ({gen_time:.1f}s total)")
print(f"\n  Prompt: {prompt}")
print(f"  Output: {out_text}")

# ─── Summary ──────────────────────────────────────────────────────────
print(f"\n── Summary ──")
print(f"  Law:       {n_params:,} params")
print(f"  Model:     {n_full:,} params")
print(f"  Ratio:     {n_params/n_full*100:.2f}%")
print(f"  Speed:     {t_law/t_full:.1f}× full model")
print(f"  Quality:   NLL delta {nll_law-nll_full:+.4f}")
print(f"  Gen speed: {gen_time/max_new*1000:.0f}ms/tok")
print(f"  No training needed — zero-shot drop-in replacement.")
